<?php

return Makhan\CS\Config\Config::create()
    ->setUsingLinter(false)
    ->setUsingCache(true)
    ->finder(
        Makhan\CS\Finder\DefaultFinder::create()
            ->in(__DIR__)
            ->exclude(array(
                // directories containing files with content that is autogenerated by `var_export`, which breaks CS in output code
                'src/Makhan/Component/DependencyInjection/Tests/Fixtures',
                'src/Makhan/Component/Routing/Tests/Fixtures/dumper',
                // fixture templates
                'src/Makhan/Component/Templating/Tests/Fixtures/templates',
                // resource templates
                'src/Makhan/Bundle/FrameworkBundle/Resources/views/Form',
            ))
            // file content autogenerated by `var_export`
            ->notPath('src/Makhan/Component/Translation/Tests/fixtures/resources.php')
            // autogenerated xmls
            ->notPath('src/Makhan/Component/Console/Tests/Fixtures/application_1.xml')
            ->notPath('src/Makhan/Component/Console/Tests/Fixtures/application_2.xml')
            // yml
            ->notPath('src/Makhan/Component/Yaml/Tests/Fixtures/sfTests.yml')
            // test template
            ->notPath('src/Makhan/Bundle/FrameworkBundle/Tests/Templating/Helper/Resources/Custom/_name_entry_label.html.php')
            // explicit heredoc test
            ->notPath('src/Makhan/Bundle/FrameworkBundle/Tests/Fixtures/Resources/views/translation.html.php')
    )
;
